### PR TITLE
Address open issues and some additional improvements

### LINKED ISSUE #3: support reading input from STDIN
`rfcfold` does not support reading the input file from STDIN (using `-i /dev/stdin`). Supporting this would allow to use `rfcfold` as part of a UNIX pipeline (not only as the start), using `-o /dev/stdout`.

### LINKED ISSUE #4: Replace `gawk` use for detecting ASCII control and non-ASCII characters with a POSIX and macOS compatible solution
GNU awk is used to detect ASCII control characters and non-ASCII characters in input data. Some GNU/Linux distributions, Alpine Linux, BSD Unix derivatives, and macOS, among others, do not install GNU awk by default. Thus compatibility could be improved by using a solution based on POSIX compatible use of other tools, e.g., combining `od` and `grep`.

### LINKED ISSUE #5: Add "forced" folding
RFC 8792 describes *forced* folding of input lines that end with the folding sequence, but `rfcfold` only detects the issue and gives up. Implement *forced* folding, at least for the *fallback* strategy 2, in a POSIX compatible way to make it work on both GNU/Linux and macOS (and additional POSIX compatible operating systems).

### PR DESCRIPTION
**Pull request by auerswal**
This pull requests addresses GitHub issues #3, #4, and #5.  Forced folding is implemented for both strategies.  Additionally, it enables use of file names starting with a hyphen (`-`), which did not work.  All new functionality is tested via additions to `validate-all.sh`.

Additionally, a few tests for existing functionality that was not yet covered by tests are added to `validate-all.sh`.  Some new tests have not generally fulfilled prerequisites and are skipped if those are not fulfilled.

The `README.md` has been expanded as well.

I have tested this pull request on Ubuntu 18.04 GNU/Linux, all tests, including optional ones, have passed.

I have asked a colleague to run `validate-all.sh` on macOS and have received a report that all tests have passed or were skipped (all optional tests were skipped).

### CODE REVIEW

**Comment by auerswal** [comment]
I intend to merge this pull request in about a week.  Unless I receive a problem report, of course.

@kwatsen: Do you have time available to look at this pull request and/or test it on your Mac?

**Comment by kwatsen** [comment]
On Catalina 10.15.5, all works after `brew install grep gawk gnu-sed`:
```
all tests passed (or skipped).
```

After **only** uninstalling `gawk`,  the same behavior as above.


After **only** uninstalling `grep`, the same final summary line is displayed, in addition to the following line during the run (I'm _assuming_ this is okay/expected behavior):
```
skipping tests with folding columns 279 and 280.
```

After **only** uninstalling `gnu-sed`, the same final summary line above is _incorrectly_ displayed, as the following line appears during the run:
```
<snip>
testing example-2.txt...okay.
sed: illegal option -- -
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
skipping tests with folding columns 279 and 280.
</snip>
```

**Comment by auerswal** [comment]
Thanks for the tests, Kent!

It is correct to skip the tests with folding columns 279 and 280 unless *both* GNU grep and GNU sed are available.

I am quite sure that the `sed` error message you reported occurred during probing and is thus not relevant, it did not occur as part of `rfcfold`. You should be able to provoke it by typing `sed --version` in a terminal on macOS.

I have pushed an additional commit to this branch to suppress just the irrelevant possible error messages during probing for GNU grep and GNU sed. That should fix your problem case above with GNU grep, but not GNU sed installed.

GNU awk is no longer needed in this branch and not used unless it is the `awk` implementation found first in `$PATH`, so it should not make any difference if it is installed or not.

Both GNU grep and GNU sed together are known to support folding columns of 279 and 280 (and quite a bit higher), and thus those two tests are run *only if both* are available, because only then can we *know* that that the tests should succeed.

**Comment by kwatsen** [comment]
all appears good now.  thanks!

**Comment by auerswal** [comment]
That's good to read! :-)

I'll just let it sit for a little while, and probably merge this PR and prepare a release over the weekend.

**Pull request merged**
